[package]
name = "aoc_2"
version = "0.1.0"
authors = ["Ross Larson <ross.e.larson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc_util = { path = "../aoc_util" }